services:
  mynestbackend:
    build: ./mynest-backend
    container_name: MyNestBackend
    environment:
      NEST_PORT: ${NEST_PORT}
      GATEWAY_PORT: ${GATEWAY_PORT}
    ports:
      - ${NEST_PORT}:${NEST_PORT}
      - "5555:5555" # Prisma studio
      - ${GATEWAY_PORT}:${GATEWAY_PORT}
    volumes:
      - ./mynest-backend:/mynest-backend
      - /mynest-backend/node_modules
    env_file:
      - .env

  mynestfrontend:
    build: ./mynest-frontend
    container_name: MyNestFrontend
    ports:
      - "3000:3000"
    volumes:
      - ./mynest-frontend:/mynest-frontend
      - /mynest-frontend/node_modules
    env_file:
      - .env

  mynestpostgres:
    image: postgres:latest
    container_name: MyNestPostgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  mynestadminer:
    image: adminer:latest
    container_name: MyNestAdminer
    restart: always
    ports:
      - 8080:8080

  mynestmaildev:
    image: maildev/maildev
    container_name: MyNestMailDev
    ports:
      - 1080:1080
      - 1025:1025

volumes:
  mynest-backend:
  mynest-frontend:
  pgdata:
