services:
  kittybackend:
    build: ./kitty-backend
    container_name: KittyBackend
    environment:
      NEST_PORT: ${NEST_PORT}
      GATEWAY_PORT: ${GATEWAY_PORT}
    ports:
      - ${NEST_PORT}:${NEST_PORT}
      - "5555:5555" # Prisma studio
      - ${GATEWAY_PORT}:${GATEWAY_PORT}
    volumes:
      - ./kitty-backend:/kitty-backend
      - /kitty-backend/node_modules
    env_file:
      - .env

  kittyfrontend:
    build: ./kitty-frontend
    container_name: KittyFrontend
    ports:
      - "3000:3000"
    volumes:
      - ./kitty-frontend:/kitty-frontend
      - /kitty-frontend/node_modules
    env_file:
      - .env

  kittypostgres:
    image: postgres:latest
    container_name: KittyPostgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  kittyadminer:
    image: adminer:latest
    container_name: KittyAdminer
    restart: always
    ports:
      - 8080:8080

  kittymaildev:
    image: maildev/maildev
    container_name: KittyMailDev
    ports:
      - 1080:1080
      - 1025:1025

volumes:
  kitty-backend:
  kitty-frontend:
  pgdata:
