FROM node:23-slim

RUN apt-get update -y && apt-get install -y procps openssl

WORKDIR /mynest-backend

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE ${NEST_PORT} 
EXPOSE ${GATEWAY_PORT}

CMD ["npm", "run", "start:dev", "--", "--host", "0.0.0.0", "--port", "${NEST_PORT}"]