FROM node:23-slim

RUN apt-get update -y && apt-get install -y procps openssl

WORKDIR /kitty-backend

COPY package*.json ./

RUN npm install

COPY . .

# RUN npx prisma generate

EXPOSE 3000

CMD ["npm", "run", "start:dev", "--", "--host", "0.0.0.0", "--port", "3000"]